---
before:
  hooks:
    - go mod download
    - go test ./...
builds:
  - main: ./cmd/cook-docs
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    goos:
      - darwin
      - linux
      - windows
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "[ci-skip]"

signs:
  - artifacts: checksum
    args: ["-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

release:
  draft: true

brews:
  - tap:
      owner: nicholaswilde
      name: homebrew-tap
    folder: Formula
    homepage: https://nicholaswilde.io/cook-docs
    description: A tool for automatically generating markdown documentation for cooklang recipes
    install: |
      bin.install "cook-docs"
    test: |
      system "#{bin}/cook-docs --version"
    license: Apache-2.0

scoop:
  bucket:
    owner: nicholaswilde
    name: scoop-bucket
  folder: bucket
  homepage: https://nicholaswilde.io/cook-docs
  description: A tool for automatically generating markdown documentation for cooklang recipes
  license: Apache-2.0
