---
version: '3'

vars:
  ROOT_DIR:
    sh: git rev-parse --show-toplevel
  PORT: 8000

tasks:
  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
      - rm -rf dist cook-docs
  coverage:
    desc: Run tests
    cmds:
      - cargo test
  dist:
    desc: Create production release
    cmds:
      - cargo build --release
  deps:
    desc: Download dependencies
    cmds:
      - cargo fetch
  dry-run:
    desc: Perform a dry run
    cmds:
      - cargo run -- --recipe-search-root testdata --dry-run
  debug:
    desc: Run program with debug logs
    cmds:
      - >
        cargo run -- --recipe-search-root testdata \
        --template-files testdata/recipe.md.gotmpl \
        --log-level debug --dry-run
  fmt:
    desc: Format Rust code
    cmds:
      - cargo fmt --all
  help:
    desc: Show app help
    cmds:
      - cargo run -- --help
  jsonify:
    desc: Jsonify the recipe
    cmds:
      - cargo run -- --jsonify
  lint:
    desc: Lint the project
    cmds:
      - yamllint-rs .
      - cargo clippy -- -D warnings
  run:
    desc: Run program
    cmds:
      - cargo run -- --recipe-search-root testdata
  serve:
    desc: Serve a zensical server
    cmds:
      - uv run zensical serve -a 0.0.0.0:{{ .PORT }}
  test:
    desc: Run Rust tests
    cmds:
      - cargo test
  default:
    desc: Lists tasks with or without a description
    cmds:
      - task -a
    silent: true
