---
name: release

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    name: Build Release Asset
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            os_name: Linux
            arch: x86_64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            os_name: Linux
            arch: arm64
          - target: arm-unknown-linux-gnueabi
            os: ubuntu-latest
            os_name: Linux
            arch: armv6
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
            os_name: Linux
            arch: armv7
          - target: x86_64-apple-darwin
            os: macos-latest
            os_name: Darwin
            arch: x86_64
          - target: aarch64-apple-darwin
            os: macos-latest
            os_name: Darwin
            arch: arm64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            os_name: Windows
            arch: x86_64
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            os_name: Windows
            arch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          TAG_NAME="${{ github.ref_name }}"
          VERSION="${TAG_NAME#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload binaries to release
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: cook-docs
          target: ${{ matrix.target }}
          archive: cook-docs_${{ steps.get_version.outputs.version }}_${{ matrix.os_name }}_${{ matrix.arch }}
          tar: all
          zip: none
          token: ${{ secrets.GITHUB_TOKEN }}
