---
name: test
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ['**']
  workflow_dispatch:
  push:
    paths:
      - '**.go'

jobs:
  full_ci:
    strategy:
      matrix:
        go_version: [1.18.x]

    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: run tests
        run: go test -json ./... > test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: test.json
