---
name: test
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ['**']
  workflow_dispatch:
  push:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yaml'
      - '**.yml'

jobs:
  full_ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install yamllint-rs
        run: cargo install yamllint-rs

      - name: Lint YAML files
        run: yamllint-rs .
